title: 動物農莊
description: 晚安．月亮─床邊故事：動物農莊
time: Tue, 26 Mar 2024 05:03:41 +0000
items:
  - title: 00. 動物農莊
    size: 935550
    duration: 94
  - title: 01. 老少校的夢
    size: 4612409
    duration: 473
  - title: 02. 偉大的理想
    size: 4762718
    duration: 505
  - title: 03. 英格蘭之獸
    size: 5016482
    duration: 521
  - title: 04. 驅逐人類
    size: 5372430
    duration: 539
  - title: 05. 動物農莊
    size: 4464873
    duration: 451
  - title: 06. 動物的誡律
    size: 3742679
    duration: 380
  - title: 07. 自立更生
    size: 5168729
    duration: 523
  - title: 08. 共同學習
    size: 5509855
    duration: 555
  - title: 09. 蘋果的滋味
    size: 4727737
    duration: 485
  - title: 10. 鴿子佈道
    size: 4860856
    duration: 479
  - title: 11. 牛棚之戰
    size: 4605732
    duration: 460
  - title: 12. 再次獲勝
    size: 4532422
    duration: 457
  - title: 13. 榮譽勳章
    size: 4871346
    duration: 505
  - title: 14. 茉莉回歸人類
    size: 4074795
    duration: 421
  - title: 15. 風車之爭
    size: 4263864
    duration: 436
  - title: 16. 雪球被驅逐
    size: 5168542
    duration: 530
  - title: 17. 權力轉移
    size: 3910293
    duration: 406
  - title: 18. 新領導
    size: 4374596
    duration: 454
  - title: 19. 建造風車
    size: 4825617
    duration: 505
  - title: 20. 眾志成城
    size: 5194407
    duration: 529
  - title: 21. 與人交易
    size: 4501625
    duration: 463
  - title: 22. 豬睡床鋪了！
    size: 5153969
    duration: 511
  - title: 23. 嫁禍
    size: 4953960
    duration: 502
  - title: 24. 糧食缺乏
    size: 4820248
    duration: 491
  - title: 25. 混淆視聽
    size: 4062065
    duration: 425
  - title: 26. 散佈謠言
    size: 4453208
    duration: 466
  - title: 27. 大清算
    size: 4660700
    duration: 478
  - title: 28. 貓咪出走
    size: 4773926
    duration: 511
  - title: 29. 拿破崙頌
    size: 4659939
    duration: 489
  - title: 30. 木材風波
    size: 4581085
    duration: 474
  - title: 31. 出爾反爾
    size: 4934471
    duration: 504
  - title: 32. 風車終結
    size: 5064059
    duration: 522
  - title: 33. 開酒戒
    size: 4504956
    duration: 469
  - title: 34. 拿破崙生病了？
    size: 4905239
    duration: 507
  - title: 35. 小豬上學
    size: 4056741
    duration: 424
  - title: 36. 豬是豬，狗是狗
    size: 4782198
    duration: 496
  - title: 37. 芭普的悲歌
    size: 4731919
    duration: 493
  - title: 38. 兩條腿是壞的？
    size: 4012861
    duration: 415
  - title: 39. 學人類走路的豬
    size: 5386043
    duration: 556
  - title: 40. 文明的動物？
    size: 4098132
    duration: 432
  - title: 41. 第二座風車
    size: 5017543
    duration: 515
  - title: 42. 人豬無分別
    size: 5585363
    duration: 581
